---
apiVersion: v1
kind: Namespace
metadata:
  name: splunkeks
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: gp3
  encrypted: "true"
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
    - ap-southeast-1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: Secret
metadata:
  name: splunk-credential
  namespace: splunkeks
type: Opaque
data:
  password: Q2hhbmdlZCE=
  idx_key: aW5kZXhlcl9rZXk=
  idx_discovery_key: aW5kZXhlcl9kaXNjb3Zlcnlfa2V5
  idx_label: aW5kZXhlcl9jbHVzdGVy
  shc_key: aW5kZXhlcl9rZXk=
  shc_label: aW5kZXhlcl9jbHVzdGVy
